### ISSUE TITLE
ACmix Fully Connected in Conv branch

### ISSUE THREAD

**Issue by HerrYu123** [LeapLabTHU/ACmix#5]
I noticed that this part of the paper is '3N×k^2N'，but in the code is '3N×k^2'. Is there a mistake here or am I understanding it wrong?

**Comment by Panxuran** [comment]
There is a mistake in the paper, and the correct form of fully connected layer should be '3N×k^2' as in the code. The N groups for convolution branch are achieved by the group convolution.

Thanks for pointing out this issue. The paper will be modified to the correct form.

I will now close the issue. Feel free to reopen it if you have other questions.

**Comment by 17860511195** [comment]
如果是k^2,那么后面哪来的N组呢，应该是k^2*N吧代码错了，论文没错，要不然怎么对应的上，我现在对本文的内容持怀疑态度了。希望能得到你的解答。

**Comment by 17860511195** [comment]
其实你是N组，每一组都是K^2个（H,W,C/N）的张量组合成1个（H,W,C/N）的张量，然后再拼接才是（H,W,C/N）*N=（H,W,C）

**Comment by yuwanting828** [comment]
请问
采用一个轻量级的全连接层( 3N×(k^2)N )并生成 k^2 个特征图是什么意思呀
