### ISSUE TITLE
Is it a typo mistake?

### ISSUE THREAD

**Issue by cd70zyx** [LeapLabTHU/ACmix#6]
ResNet/test_bottleneck.py
line 101
original:
f_conv = f_all.permute(0, 2, 1, 3).reshape(x.shape[0], -1, x.shape[-1], x.shape[-1])
but I think it should be:
f_conv = f_all.permute(0, 2, 1, 3).reshape(x.shape[0], -1, x.shape[-2], x.shape[-1])
to maintain the shape of input height and width.
I do not know if it is correct. Looking forward to your reply. Thanks.

**Comment by Panxuran** [comment]
You are right, and the correct code should be 
f_conv = f_all.permute(0, 2, 1, 3).reshape(x.shape[0], -1, x.shape[-2], x.shape[-1])

As the widely used classification benchmarks (cifar / imagenet) have the same input height and width, the original code can work well. Thanks for pointing out this issue, and I will update the code for better clarity.

I will now close the issue. Feel free to reopen it if you have other questions.

**Comment by wo0423** [comment]
> ResNet/test_bottleneck.py line 101 original: f_conv = f_all.permute(0, 2, 1, 3).reshape(x.shape[0], -1, x.shape[-1], x.shape[-1]) but I think it should be: f_conv = f_all.permute(0, 2, 1, 3).reshape(x.shape[0], -1, x.shape[-2], x.shape[-1]) to maintain the shape of input height and width. I do not know if it is correct. Looking forward to your reply. Thanks.

excuse me, i wonder how this step realized?I reported an error when running
![image](https://user-images.githubusercontent.com/59550614/206889666-2d2e84ce-ae12-4a89-97e3-22569ec91b90.png)

ResNet/test_bottleneck.py
line 93
att = (q_att.unsqueeze(2)*(unfold_k + q_pe.unsqueeze(2) - unfold_rpe)).sum(1)  # (b*head, head_dim, 1, h_out, w_out) * (b*head, head_dim, k_att^2, h_out, w_out) -> (b*head, k_att^2, h_out, w_out)
